# Sample config for Prometheus.

global:
  scrape_interval:     30s # By default, scrape targets every 30 seconds.
  evaluation_interval: 30s # By default, scrape targets every 30 seconds.
  # scrape_timeout is set to the global default (10s).
  scrape_timeout: 30s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'miraheze'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 35 seconds.
    scrape_interval: 30s
    scrape_timeout: 30s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']

  - job_name: node
    # If prometheus-node-exporter is installed, grab stats about the local
    # machine by default.
    static_configs:
      - targets: [
        'bacula1.miraheze.org:9100', # Standard exporter
        'cp2.miraheze.org:9100',
        'cp4.miraheze.org:9100',
        'cp5.miraheze.org:9100',
        'db4.miraheze.org:9100',
        'misc1.miraheze.org:9100',
        'misc2.miraheze.org:9100',
        'misc3.miraheze.org:9100',
        'mw1.miraheze.org:9100',
        'mw2.miraheze.org:9100',
        'mw3.miraheze.org:9100',
        'nfs1.miraheze.org:9100',
        'ns1.miraheze.org:9100',
        'puppet1.miraheze.org:9100',
        'swift1.miraheze.org:9100',
        'test1.miraheze.org:9100',
        'cp2.miraheze.org:9131', # Varnish exporter
        'cp4.miraheze.org:9131',
        'cp5.miraheze.org:9131',
      ]
