worker_heartbeat_timeout: 115000

num_workers: 0

worker_heap_limit_mb: 90

logging:
  level: info

wiki: &wiki
<%- @wikis.each_pair do |wiki, value| -%>
<%- if value == true -%>
        - uri: 'https://<%= wiki %>.miraheze.org/w/api.php'
          domain: '<%= wiki %>.miraheze.org'
<%- else -%>
        - uri: 'https://<%= value %>/w/api.php'
          domain: '<%= value %>'
<%- end -%>
<%- end -%>

services:
  - module: /srv/parsoid/lib/index.js
    entrypoint: apiServiceWorker
    conf:
      mwApis: *wiki
      loadWMF: false
      debug: false
      usePHPPreProcessor: true
      useSelser: true
      useBatchAPI: true
      linting: true
      linterSendAPI: false
      strictSSL: true
      useWorker: true
      cpu_workers: 1
      nativeGallery: false
      timeouts:
        request: 110000
        mwApi:
          batch: 145000
      limits:
        wt2html:
          maxTableCells: 40000
          maxListItems: 40000
